c WARNING: for repeatability, setting FPU to use double precision
c Problem Statistics:
c
c [33mBenchmark Information[0m
c Number of variables: 135
c Number of clauses: 1152
c Number of literals: 6441
c Parse time: 0.00
c
c [33md-DNNF Information[0m
c Number of nodes: 7206875
c Number of edges: 14716753
c 
c Final time: 378.243064
c 
s 89912077
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Traceback (most recent call last):
  File "../tools/query_wrapper.py", line 50, in <module>
    print("ANSWER:", float(output.decode('utf-8').split()[-1]))
ValueError: could not convert string to float: 'yet...'
Command exited with non-zero status 1
	Command being timed: "python ../tools/query_wrapper.py -m 32 d4 data/mc2022_track2_115.cnf.minic2d.cnf"
	User time (seconds): 608.92
	System time (seconds): 451.84
	Percent of CPU this job got: 90%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 19:31.06
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 27998012
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 9553340
	Voluntary context switches: 189625
	Involuntary context switches: 1570
	Swaps: 0
	File system inputs: 0
	File system outputs: 0
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
